commands:
  - "?"
  - "pl"
  - "about"
  - "version"
  - "ver"
  - "plugins"
  - "bukkit:?"
  - "bukkit:pl"
  - "bukkit:about"
  - "bukkit:version"
  - "bukkit:ver"
  - "bukkit:plugins"
  - "minecraft:pl"
  - "minecraft:plugins"
  - "minecraft:about"
  - "minecraft:version"
  - "minecraft:ver"