name: NoPluginsCommand
version: ${project.version}
main: net.noodles.pl.nopluginscommand.NoPluginsCommand
authors: [BGHDDevelopmentLLC]
description: Blocks /plugin, /about, /version, and more!
website: https://bghddevelopment.com
api-version: 1.20
permissions:
  nopluginscommand.bypass:
    default: false
    description: allows access to forbidden commands
